name: "GH Arxiv Posterbot"
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 1,3,16,19,22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Typst
        uses: typst-community/setup-typst@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: scrape and run
        run: python3 paperbot.py
        env:
          BSKYBOT: ${{ secrets.BSKYBOT }}
          BSKYPWD: ${{ secrets.BSKYPWD }}
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          push: true
          default_author: github_actions
